-- Database: progest2
CREATE DATABASE IF NOT EXISTS progest2;
USE progest2;

CREATE TABLE IF NOT EXISTS dono (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(80) NOT NULL,
  cpf_cnpj VARCHAR(18) NOT NULL UNIQUE,
  email VARCHAR(120),
  telefone VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS propriedade (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  municipio VARCHAR(80) NOT NULL,
  estado VARCHAR(80) NOT NULL,
  area_total_ha DECIMAL(10,2) NOT NULL,
  dono_id INT NOT NULL,
  FOREIGN KEY (dono_id) REFERENCES dono(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS animal (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tipo VARCHAR(80) NOT NULL,
  raca VARCHAR(80)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lote (
  id INT AUTO_INCREMENT PRIMARY KEY,
  propriedade_id INT NOT NULL,
  animal_id INT NOT NULL,
  quantidade INT NOT NULL,
  data_registro DATE,
  FOREIGN KEY (propriedade_id) REFERENCES propriedade(id) ON DELETE CASCADE,
  FOREIGN KEY (animal_id) REFERENCES animal(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Usuários para autenticação
CREATE TABLE IF NOT EXISTS usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;